### ISSUE TITLE
Error when running quick demo

### ISSUE THREAD

**Issue by trydonot** [wei-mao-2019/LearnTrajDep#16]
Hello,

when I try to run :
`python main.py --epoch 5 --input_n 10 --output 10 --dct_n 20 --data_dir home/h3.6m/dataset/`

I get to the training: 
>>> data loaded !
>>> train data 182327
>>> validation data 28560
==========================
>>> epoch: 1 | lr: 0.00050

And then the following error occurs:
```
Traceback (most recent call last):
  File "main.py", line 340, in <module>
    main(option)
  File "main.py", line 116, in main
    dim_used=train_dataset.dim_used, dct_n=dct_n)
  File "main.py", line 189, in train
    outputs = model(inputs)
  File "C:\Users\Anaconda3\envs\test_prediction\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\PycharmProjects\human_prediction\utils\model.py", line 117, in forward
    y = self.gc1(x)
  File "C:\Users\Anaconda3\envs\test_prediction\lib\site-packages\torch\nn\modules\module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\PycharmProjects\human_prediction\utils\model.py", line 37, in forward
    support = torch.matmul(input, self.weight)
  File "C:\Users\Anaconda3\envs\test_prediction\lib\site-packages\torch\functional.py", line 192, in matmul
    output = torch.mm(tensor1, tensor2)
RuntimeError: cublas runtime error : the GPU program failed to execute at C:/Anaconda2/conda-bld/pytorch_1519501749874/work/torch/lib/THC/THCBlas.cu:247
```

Can you please help me?

**Comment by wei-mao-2019** [comment]
It could because of your pytorch version. Please find our version in readme file.
