### ISSUE TITLE
I got a problem when I run demo.py

### ISSUE THREAD

**Issue by helloful** [wei-mao-2019/LearnTrajDep#18]
When I try to run demo.py use pretrained model
`model_path_len = './checkpoint/pretrained/h36m_in10_out25_dctn35.pth.tar'`

and I got a peoblem as follow:
`
Traceback (most recent call last):
  File "G:\2021 summary\Graduation project\LearnTrajDep-master\demo.py", line 117, in <module>
    main(option)
  File "G:\2021 summary\Graduation project\LearnTrajDep-master\demo.py", line 89, in main
    outputs = model(inputs)
  File "D:\softwave\Python3.9\Lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\2021 summary\Graduation project\LearnTrajDep-master\utils\model.py", line 117, in forward
    y = self.gc1(x)
  File "D:\softwave\Python3.9\Lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "G:\2021 summary\Graduation project\LearnTrajDep-master\utils\model.py", line 37, in forward
    support = torch.matmul(input, self.weight)
RuntimeError: mat1 dim 1 must match mat2 dim 0

Process finished with exit code 1

`

**Comment by Neuzly1** [comment]
I also have  this problem, do u remember how to save it?
